### ISSUE TITLE
TitleParser exception causing crash

### ISSUE THREAD

**Issue by Nedlinin** [martijnboers/BlotterTrax#43]
Looks like we need to test song_title for null in TitleParser before we try any further ops.  Otherwise, we sometimes crash when the parsing fails out.

```
Traceback (most recent call last):
  File "./main.py", line 108, in daemon
    self._run()
  File "./main.py", line 53, in _run
    parsed_submission = TitleParser.create_parsed_submission_from_submission(submission)
  File "/usr/src/app/blottertrax/helper/title_parser.py", line 46, in create_parsed_submission_from_submission
    song_title = re.sub(r"\(.*\)", "", song_title)
  File "/usr/local/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 108, in daemon
    self._run()
  File "./main.py", line 53, in _run
    parsed_submission = TitleParser.create_parsed_submission_from_submission(submission)
  File "/usr/src/app/blottertrax/helper/title_parser.py", line 46, in create_parsed_submission_from_submission
    song_title = re.sub(r"\(.*\)", "", song_title)
  File "/usr/local/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 116, in <module>
    BlotterTrax().daemon()
  File "./main.py", line 112, in daemon
    self.daemon()
  File "./main.py", line 112, in daemon
    self.daemon()
  File "./main.py", line 112, in daemon
    self.daemon()
  [Previous line repeated 328 more times]
  File "./main.py", line 110, in daemon
    traceback.print_exc(file=sys.stdout)
  File "/usr/local/lib/python3.7/traceback.py", line 163, in print_exc
    print_exception(*sys.exc_info(), limit=limit, file=file, chain=chain)
  File "/usr/local/lib/python3.7/traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/usr/local/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  File "/usr/local/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  File "/usr/local/lib/python3.7/traceback.py", line 497, in __init__
    _seen=_seen)
  [Previous line repeated 328 more times]
  File "/usr/local/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/usr/local/lib/python3.7/traceback.py", line 333, in extract
    limit = getattr(sys, 'tracebacklimit', None)
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by TcMaX** [comment]
This should be fixed in #14
